events {
    worker_connections 1024;
}

http {
    server {
        # Слушаем HTTPS
        listen 443 ssl;
        server_name localhost;

        # Пути к сертификатам
        ssl_certificate     /etc/nginx/certs/localhost.pem;
        ssl_certificate_key /etc/nginx/certs/localhost-key.pem;

        # Рекомендуемые настройки безопасности для TLS
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            # host.docker.internal - сеть винды
            proxy_pass http://host.docker.internal:8000;

            # Стандартные заголовки для проксирования
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Указываем бэкенду, что изначальный запрос был по HTTPS
            proxy_set_header X-Forwarded-Proto https;

            # Пробрасываем кастомные заголовки для авторизации и аналитики
            proxy_set_header Authorization $http_authorization;
            proxy_set_header User-Agent $http_user_agent;

            # Настройки для поддержки WebSockets
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }
    }

    # Редирект с HTTP на HTTPS
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }
}