spring:
  application:
    name: gateway-service

  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

  profiles:
    active: dev