spring:
  application:
    name: pulse-gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          routes:
            # Identity service
            - id: identity-service
              uri: ${IDENTITY_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/auth/**,/api/users/**
              filters:
                - StripPrefix=0

            - id: identity-service-docs
              uri: ${IDENTITY_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/v3/api-docs/identity-service
              filters:
                - RewritePath=/v3/api-docs/identity-service, /v3/api-docs

            # Messenger service
            - id: messenger-service
              uri: ${MESSENGER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/message
              filters:
                - StripPrefix=0

            - id: messenger-service-docs
              uri: ${messenger_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/v3/api-docs/messenger-service
              filters:
                - RewritePath=/v3/api-docs/messenger-service, /v3/api-docs
jwt:
  secret: ${JWT_SECRET:dev-super-secret-key-that-is-at-least-256-bits-long-for-hmac-sha256-algorithm}

internal:
  security:
    token: "${INTERNAL_SECRET:super-safe-dev-key}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      access: unrestricted

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG