CREATE TABLE attachments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    message_id        BIGINT                                    NOT NULL,
    file_name         VARCHAR(255)                              NOT NULL,
    file_type         VARCHAR(255)                              NOT NULL,
    file_size         BIGINT                                    NOT NULL,
    minio_object_name VARCHAR(255)                              NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_attachments PRIMARY KEY (id)
);

CREATE TABLE channel_read_states
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id              BIGINT                                  NOT NULL,
    channel_id           BIGINT                                  NOT NULL,
    last_read_message_id BIGINT,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_channel_read_states PRIMARY KEY (id)
);

CREATE TABLE chat_groups
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    owner_id    BIGINT,
    name        VARCHAR(255),
    type        VARCHAR(20)                               NOT NULL,
    dm_hash_key VARCHAR(50),
    features    JSONB,
    avatar_url  VARCHAR(500),
    description TEXT,
    is_deleted  BOOLEAN                     DEFAULT FALSE NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chat_groups PRIMARY KEY (id)
);

CREATE TABLE group_members
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id    BIGINT                                  NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    permissions BIGINT                                  NOT NULL,
    joined_at   TIMESTAMP WITHOUT TIME ZONE,
    muted       BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_group_members PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    author_id       BIGINT                                    NOT NULL,
    channel_id      BIGINT                                    NOT NULL,
    content         TEXT,
    reply_to_id     BIGINT,
    forward_from_id BIGINT,
    is_edited       BOOLEAN                     DEFAULT FALSE NOT NULL,
    is_deleted      BOOLEAN                     DEFAULT FALSE NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE text_channels
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id   BIGINT                                  NOT NULL,
    name       VARCHAR(50)                             NOT NULL,
    topic      VARCHAR(200),
    position   INTEGER,
    is_deleted BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_text_channels PRIMARY KEY (id)
);

ALTER TABLE channel_read_states
    ADD CONSTRAINT uc_channel_read_states_user_channel UNIQUE (user_id, channel_id);

ALTER TABLE chat_groups
    ADD CONSTRAINT uc_chat_groups_dm_hash_key UNIQUE (dm_hash_key);

ALTER TABLE group_members
    ADD CONSTRAINT uc_group_members_group_user UNIQUE (group_id, user_id);

CREATE INDEX idx_channel_group_position ON text_channels (group_id, position);

CREATE INDEX idx_group_created_at ON chat_groups (created_at);

CREATE INDEX idx_group_member_joined_at ON group_members (joined_at);

CREATE INDEX idx_group_member_user_id ON group_members (user_id);

CREATE INDEX idx_group_owner_id ON chat_groups (owner_id);

CREATE INDEX idx_group_type ON chat_groups (type);

CREATE INDEX idx_message_author_id ON messages (author_id);

CREATE INDEX idx_message_channel_created ON messages (channel_id, created_at DESC);

CREATE INDEX idx_message_created_at ON messages (created_at);

CREATE INDEX idx_read_state_user_id ON channel_read_states (user_id);

ALTER TABLE attachments
    ADD CONSTRAINT FK_ATTACHMENTS_ON_MESSAGE FOREIGN KEY (message_id) REFERENCES messages (id);

CREATE INDEX idx_attachment_message_id ON attachments (message_id);

ALTER TABLE channel_read_states
    ADD CONSTRAINT FK_CHANNEL_READ_STATES_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES text_channels (id);

CREATE INDEX idx_read_state_channel_id ON channel_read_states (channel_id);

ALTER TABLE group_members
    ADD CONSTRAINT FK_GROUP_MEMBERS_ON_GROUP FOREIGN KEY (group_id) REFERENCES chat_groups (id);

CREATE INDEX idx_group_member_group_id ON group_members (group_id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES text_channels (id);

CREATE INDEX idx_message_channel_id ON messages (channel_id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_FORWARD_FROM FOREIGN KEY (forward_from_id) REFERENCES messages (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_REPLY_TO FOREIGN KEY (reply_to_id) REFERENCES messages (id);

CREATE INDEX idx_message_reply_to ON messages (reply_to_id);

ALTER TABLE text_channels
    ADD CONSTRAINT FK_TEXT_CHANNELS_ON_GROUP FOREIGN KEY (group_id) REFERENCES chat_groups (id);

CREATE INDEX idx_channel_group_id ON text_channels (group_id);